### ISSUE TITLE
Verify local users statistics; fix if broken

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/TweetSets#49]
Verify that local users stats on https://tweetsets.library.gwu.edu/stats are correct.   It's possible that they may be correct for the last 6 months (due to lack of #48) but this warrants verification.

Repair if broken.

**Comment by dolsysmith** [comment]
Need to clarify what is meant by "local" users. As I'm reading the code (`tweetset_server.py`, lines 539-553), the `_is_local` flag is triggered only in a couple of situations:

1. When the app is being run in `DEBUG` mode
2. When the parameter in `app.config['SERVER_MODE']` is set to `local`.

**Comment by dolsysmith** [comment]
An issue exists in line 85 of `stats.py`:
```
        return list(map(SourceDatasetStat._make, self._get_conn().execute(sql, params).fetchmany(limit)))
```
The `limit` parameter is set to 10 by default. When there are more than 10 datasets in the database, this limit causes some counts to be lost, because the original code creates a pivot table manually (as it were) with Python code, stitching together multiple SQL queries, _each of which shows only the top 10 results_. 

I have verified this by analyzing the `stats.db` database from production against the output of the `stats.py` code. 

A quick but temporary fix would be to up the `limit` to 100. But a more sustainable solution will require a refactor of the relevant portions of `stats.py`. (By the way, I have not tested this for the Derivative stats, only for the Source Dataset stats, but given the code, I suspect the problem is the same.)

**Comment by dolsysmith** [comment]
What I propose: to refactor both `source_datasets_stats` and `derivatives_stats` to use a single complex SQL query in each case (with `JOIN`'s) to derive the tables. I believe this will fix the issue and eliminate the need for the code in `source_datasets_stats_merge` and `derivatives_stats_merge`.
