### ISSUE TITLE
Consider disabling multi-select across datasets

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/TweetSets#85]
This has led to a job that selected ALL datasets.  A user with a meaningful use case can always get individual data set extracts, and combine them.

**Comment by lwrubel** [comment]
When changing the form to only allow one source dataset selection (via a radio button instead of checkbox?) also apply accessibility remediation. SiteImprove flagged the following:

"Form elements are not grouped. When a form contains elements that are logically connected to each other it is necessary to group them. The form contains check boxes and/or radio buttons that are not grouped and named, using a 'fieldset' with a descriptive 'legend' or the WAI-ARIA attribute role="group" (for check boxes) or role="radiogroup" (for radio buttons) with a descriptive 'aria-labelledby' or 'aria-label'."

Also confirm that the update does not trigger an accessibility issue with the radio button, e.g. "Input field has no description".

**Comment by lwrubel** [comment]
Based on [WebAIM guidance on radio buttons](https://webaim.org/techniques/forms/controls#radio), not implementing a fieldset or group.
